-- Consent Management API Database Schema
-- Version: 1.0.0
-- Description: Initial schema for consent management system

-- Drop tables if they exist (for clean reinstall)
DROP TABLE IF EXISTS FS_CONSENT_FILE;
DROP TABLE IF EXISTS FS_CONSENT_ATTRIBUTE;
DROP TABLE IF EXISTS FS_CONSENT_STATUS_AUDIT;
DROP TABLE IF EXISTS FS_CONSENT_AUTH_RESOURCE;
DROP TABLE IF EXISTS CONSENT_PURPOSE_MAPPING;
DROP TABLE IF EXISTS CONSENT_PURPOSE;
DROP TABLE IF EXISTS FS_CONSENT;

-- Main consent table
CREATE TABLE IF NOT EXISTS FS_CONSENT (
  CONSENT_ID            VARCHAR(255) NOT NULL,
  RECEIPT               JSON NOT NULL,
  CREATED_TIME          BIGINT NOT NULL,
  UPDATED_TIME          BIGINT NOT NULL,
  CLIENT_ID             VARCHAR(255) NOT NULL,
  CONSENT_TYPE          VARCHAR(64) NOT NULL,
  CURRENT_STATUS        VARCHAR(64) NOT NULL,
  CONSENT_FREQUENCY     INT DEFAULT NULL,
  VALIDITY_TIME         BIGINT DEFAULT NULL,
  RECURRING_INDICATOR   BOOLEAN DEFAULT NULL,
  ORG_ID                VARCHAR(255) DEFAULT 'DEFAULT_ORG',
  PRIMARY KEY (CONSENT_ID, ORG_ID),
  INDEX idx_client_id (CLIENT_ID),
  INDEX idx_consent_type (CONSENT_TYPE),
  INDEX idx_current_status (CURRENT_STATUS),
  INDEX idx_created_time (CREATED_TIME),
  INDEX idx_org_id (ORG_ID)
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Authorization resource table
CREATE TABLE IF NOT EXISTS FS_CONSENT_AUTH_RESOURCE (
  AUTH_ID           VARCHAR(255) NOT NULL,
  CONSENT_ID        VARCHAR(255) NOT NULL,
  AUTH_TYPE         VARCHAR(255) NOT NULL,
  USER_ID           VARCHAR(255) DEFAULT NULL,
  AUTH_STATUS       VARCHAR(255) NOT NULL,
  UPDATED_TIME      BIGINT NOT NULL,
  RESOURCE          TEXT DEFAULT NULL,
  ORG_ID            VARCHAR(255) DEFAULT 'DEFAULT_ORG',
  PRIMARY KEY (AUTH_ID, ORG_ID),
  INDEX idx_consent_id (CONSENT_ID),
  INDEX idx_user_id (USER_ID),
  INDEX idx_auth_status (AUTH_STATUS),
  CONSTRAINT FK_FS_CONSENT_AUTH_RESOURCE 
    FOREIGN KEY (CONSENT_ID, ORG_ID) 
    REFERENCES FS_CONSENT (CONSENT_ID, ORG_ID) 
    ON DELETE CASCADE
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Status audit table for tracking consent status changes
CREATE TABLE IF NOT EXISTS FS_CONSENT_STATUS_AUDIT (
  STATUS_AUDIT_ID   VARCHAR(255) NOT NULL,
  CONSENT_ID        VARCHAR(255) NOT NULL,
  CURRENT_STATUS    VARCHAR(64) NOT NULL,
  ACTION_TIME       BIGINT NOT NULL,
  REASON            TEXT DEFAULT NULL,
  ACTION_BY         VARCHAR(255) DEFAULT NULL,
  PREVIOUS_STATUS   VARCHAR(64) DEFAULT NULL,
  ORG_ID            VARCHAR(255) DEFAULT 'DEFAULT_ORG',
  PRIMARY KEY (STATUS_AUDIT_ID, ORG_ID),
  INDEX idx_consent_id (CONSENT_ID),
  INDEX idx_action_time (ACTION_TIME),
  CONSTRAINT FK_FS_CONSENT_STATUS_AUDIT 
    FOREIGN KEY (CONSENT_ID, ORG_ID) 
    REFERENCES FS_CONSENT (CONSENT_ID, ORG_ID) 
    ON DELETE CASCADE
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Consent attributes table for key-value pairs
CREATE TABLE IF NOT EXISTS FS_CONSENT_ATTRIBUTE (
  CONSENT_ID        VARCHAR(255) NOT NULL,
  ATT_KEY           VARCHAR(255) NOT NULL,
  ATT_VALUE         TEXT NOT NULL,
  ORG_ID            VARCHAR(255) DEFAULT 'DEFAULT_ORG',
  PRIMARY KEY (CONSENT_ID, ATT_KEY, ORG_ID),
  INDEX idx_att_key (ATT_KEY),
  CONSTRAINT FK_FS_CONSENT_ATTRIBUTE 
    FOREIGN KEY (CONSENT_ID, ORG_ID) 
    REFERENCES FS_CONSENT (CONSENT_ID, ORG_ID) 
    ON DELETE CASCADE
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Consent file table for storing consent documents
CREATE TABLE IF NOT EXISTS FS_CONSENT_FILE (
  CONSENT_ID        VARCHAR(255) NOT NULL,
  CONSENT_FILE      LONGBLOB NOT NULL,
  ORG_ID            VARCHAR(255) DEFAULT 'DEFAULT_ORG',
  PRIMARY KEY (CONSENT_ID, ORG_ID),
  CONSTRAINT FK_FS_CONSENT_FILE 
    FOREIGN KEY (CONSENT_ID, ORG_ID) 
    REFERENCES FS_CONSENT (CONSENT_ID, ORG_ID) 
    ON DELETE CASCADE
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Consent purpose table
CREATE TABLE IF NOT EXISTS CONSENT_PURPOSE (
  ID            VARCHAR(255) NOT NULL,
  NAME          VARCHAR(255) NOT NULL,
  DESCRIPTION   VARCHAR(1024) DEFAULT NULL,
  ORG_ID        VARCHAR(255) DEFAULT 'DEFAULT_ORG',
  PRIMARY KEY (ID, ORG_ID),
  INDEX idx_name (NAME),
  INDEX idx_org_id (ORG_ID)
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Mapping table to link consent with purposes
CREATE TABLE IF NOT EXISTS CONSENT_PURPOSE_MAPPING (
  CONSENT_ID   VARCHAR(255) NOT NULL,
  ORG_ID       VARCHAR(255) DEFAULT 'DEFAULT_ORG',
  PURPOSE_ID   VARCHAR(255) NOT NULL,
  PRIMARY KEY (CONSENT_ID, ORG_ID, PURPOSE_ID),
  INDEX idx_consent_id (CONSENT_ID),
  INDEX idx_purpose_id (PURPOSE_ID),
  CONSTRAINT FK_CONSENT_PURPOSE_MAPPING_CONSENT 
    FOREIGN KEY (CONSENT_ID, ORG_ID)
    REFERENCES FS_CONSENT (CONSENT_ID, ORG_ID)
    ON DELETE CASCADE,
  CONSTRAINT FK_CONSENT_PURPOSE_MAPPING_PURPOSE
    FOREIGN KEY (PURPOSE_ID, ORG_ID)
    REFERENCES CONSENT_PURPOSE (ID, ORG_ID)
    ON DELETE CASCADE
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;