-- Consent Management API Database Schema
-- Version: 1.0.0
-- Description: Initial schema for consent management system

-- Drop tables if they exist (for clean reinstall)
DROP TABLE IF EXISTS CONSENT_PURPOSE_APPROVAL;
DROP TABLE IF EXISTS CONSENT_PURPOSE_GROUP_CONSENT;
DROP TABLE IF EXISTS CONSENT_PURPOSE_GROUP_MAPPING;
DROP TABLE IF EXISTS CONSENT_PURPOSE_GROUP;
DROP TABLE IF EXISTS CONSENT_ATTRIBUTE;
DROP TABLE IF EXISTS CONSENT_STATUS_AUDIT;
DROP TABLE IF EXISTS CONSENT_AUTH_RESOURCE;
DROP TABLE IF EXISTS CONSENT_PURPOSE_ATTRIBUTE;
DROP TABLE IF EXISTS CONSENT_PURPOSE;
DROP TABLE IF EXISTS CONSENT;

-- Main consent table
CREATE TABLE IF NOT EXISTS CONSENT (
  CONSENT_ID            VARCHAR(255) NOT NULL,
  CREATED_TIME          BIGINT NOT NULL,
  UPDATED_TIME          BIGINT NOT NULL,
  CLIENT_ID             VARCHAR(255) NOT NULL,
  CONSENT_TYPE          VARCHAR(64) NOT NULL,
  CURRENT_STATUS        VARCHAR(64) NOT NULL,
  CONSENT_FREQUENCY     INT DEFAULT NULL,
  VALIDITY_TIME         BIGINT DEFAULT NULL,
  RECURRING_INDICATOR   BOOLEAN DEFAULT NULL,
  DATA_ACCESS_VALIDITY_DURATION BIGINT DEFAULT NULL,
  ORG_ID                VARCHAR(255) DEFAULT 'DEFAULT_ORG',
  PRIMARY KEY (CONSENT_ID, ORG_ID),
  INDEX idx_client_id (CLIENT_ID),
  INDEX idx_consent_type (CONSENT_TYPE),
  INDEX idx_current_status (CURRENT_STATUS),
  INDEX idx_created_time (CREATED_TIME),
  INDEX idx_updated_time (UPDATED_TIME),
  INDEX idx_org_id (ORG_ID)
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Authorization resource table
CREATE TABLE IF NOT EXISTS CONSENT_AUTH_RESOURCE (
  AUTH_ID           VARCHAR(255) NOT NULL,
  CONSENT_ID        VARCHAR(255) NOT NULL,
  AUTH_TYPE         VARCHAR(255) NOT NULL,
  USER_ID           VARCHAR(255) DEFAULT NULL,
  AUTH_STATUS       VARCHAR(255) NOT NULL,
  UPDATED_TIME      BIGINT NOT NULL,
  RESOURCES                TEXT DEFAULT NULL,
  ORG_ID            VARCHAR(255) DEFAULT 'DEFAULT_ORG',
  PRIMARY KEY (AUTH_ID, ORG_ID),
  INDEX idx_consent_id (CONSENT_ID),
  INDEX idx_user_id (USER_ID),
  INDEX idx_auth_status (AUTH_STATUS),
  INDEX idx_consent_org (CONSENT_ID, ORG_ID),
  CONSTRAINT FK_CONSENT_AUTH_RESOURCE
    FOREIGN KEY (CONSENT_ID, ORG_ID)
    REFERENCES CONSENT (CONSENT_ID, ORG_ID)
    ON DELETE CASCADE
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Status audit table for tracking consent status changes
CREATE TABLE IF NOT EXISTS CONSENT_STATUS_AUDIT (
  STATUS_AUDIT_ID   VARCHAR(255) NOT NULL,
  CONSENT_ID        VARCHAR(255) NOT NULL,
  CURRENT_STATUS    VARCHAR(64) NOT NULL,
  ACTION_TIME       BIGINT NOT NULL,
  REASON            TEXT DEFAULT NULL,
  ACTION_BY         VARCHAR(255) DEFAULT NULL,
  PREVIOUS_STATUS   VARCHAR(64) DEFAULT NULL,
  ORG_ID            VARCHAR(255) DEFAULT 'DEFAULT_ORG',
  PRIMARY KEY (STATUS_AUDIT_ID, ORG_ID),
  INDEX idx_consent_id (CONSENT_ID),
  INDEX idx_action_time (ACTION_TIME),
  CONSTRAINT FK_CONSENT_STATUS_AUDIT
    FOREIGN KEY (CONSENT_ID, ORG_ID)
    REFERENCES CONSENT (CONSENT_ID, ORG_ID)
    ON DELETE CASCADE
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Consent attributes table for key-value pairs
CREATE TABLE IF NOT EXISTS CONSENT_ATTRIBUTE (
  CONSENT_ID        VARCHAR(255) NOT NULL,
  ATT_KEY           VARCHAR(255) NOT NULL,
  ATT_VALUE         TEXT NOT NULL,
  ORG_ID            VARCHAR(255) DEFAULT 'DEFAULT_ORG',
  PRIMARY KEY (CONSENT_ID, ATT_KEY, ORG_ID),
  INDEX idx_att_key (ATT_KEY),
  INDEX idx_consent_org (CONSENT_ID, ORG_ID),
  CONSTRAINT FK_CONSENT_ATTRIBUTE
    FOREIGN KEY (CONSENT_ID, ORG_ID)
    REFERENCES CONSENT (CONSENT_ID, ORG_ID)
    ON DELETE CASCADE
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Consent purpose table
CREATE TABLE IF NOT EXISTS CONSENT_PURPOSE (
  ID            VARCHAR(255) NOT NULL,
  NAME          VARCHAR(255) NOT NULL,
  DESCRIPTION   VARCHAR(1024) DEFAULT NULL,
  TYPE          VARCHAR(64) NOT NULL DEFAULT 'string',
  ORG_ID        VARCHAR(255) DEFAULT 'DEFAULT_ORG',
  PRIMARY KEY (ID, ORG_ID),
  UNIQUE KEY unique_name_per_org (NAME, ORG_ID),
  INDEX idx_name (NAME),
  INDEX idx_org_id (ORG_ID),
  INDEX idx_type (TYPE)
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Attributes for consent purposes (key/value pairs scoped to purpose + org)
CREATE TABLE IF NOT EXISTS CONSENT_PURPOSE_ATTRIBUTE (
  PURPOSE_ID       VARCHAR(255) NOT NULL,
  ATT_KEY          VARCHAR(255) NOT NULL,
  ATT_VALUE        TEXT NOT NULL,
  ORG_ID           VARCHAR(255) DEFAULT 'DEFAULT_ORG',
  PRIMARY KEY (PURPOSE_ID, ATT_KEY, ORG_ID),
  INDEX idx_att_key_purpose (ATT_KEY),
  CONSTRAINT FK_CONSENT_PURPOSE_ATTRIBUTE_PURPOSE
    FOREIGN KEY (PURPOSE_ID, ORG_ID)
    REFERENCES CONSENT_PURPOSE (ID, ORG_ID)
    ON DELETE CASCADE
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


-- Purpose group table to organize related purposes
CREATE TABLE IF NOT EXISTS CONSENT_PURPOSE_GROUP (
  ID           VARCHAR(255) NOT NULL,
  NAME         VARCHAR(255) NOT NULL,
  DESCRIPTION  VARCHAR(1024) DEFAULT NULL,
  CLIENT_ID    VARCHAR(255) NOT NULL,   -- group ownership (TPP / client)
  CREATED_TIME BIGINT NOT NULL,
  UPDATED_TIME BIGINT NOT NULL,
  ORG_ID       VARCHAR(255) DEFAULT 'DEFAULT_ORG',

  PRIMARY KEY (ID, ORG_ID),
  UNIQUE KEY uk_group_name_per_client (NAME, CLIENT_ID, ORG_ID),

  INDEX idx_group_client_id (CLIENT_ID),
  INDEX idx_group_org_id (ORG_ID),
  INDEX idx_group_name (NAME),
  INDEX idx_group_created_time (CREATED_TIME),
  INDEX idx_group_org_client (ORG_ID, CLIENT_ID)
) ENGINE=INNODB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_unicode_ci;

-- Maps purposes to groups with mandatory flag (defines group structure)
CREATE TABLE IF NOT EXISTS CONSENT_PURPOSE_GROUP_MAPPING (
  GROUP_ID     VARCHAR(255) NOT NULL,
  PURPOSE_ID   VARCHAR(255) NOT NULL,
  IS_MANDATORY BOOLEAN NOT NULL DEFAULT FALSE,
  ORG_ID       VARCHAR(255) DEFAULT 'DEFAULT_ORG',

  PRIMARY KEY (GROUP_ID, PURPOSE_ID, ORG_ID),

  INDEX idx_group_mapping_group (GROUP_ID),
  INDEX idx_group_mapping_purpose (PURPOSE_ID),
  INDEX idx_group_mapping_org (ORG_ID),

  CONSTRAINT fk_group_mapping_group
    FOREIGN KEY (GROUP_ID, ORG_ID)
    REFERENCES CONSENT_PURPOSE_GROUP (ID, ORG_ID)
    ON DELETE CASCADE,

  CONSTRAINT fk_group_mapping_purpose
    FOREIGN KEY (PURPOSE_ID, ORG_ID)
    REFERENCES CONSENT_PURPOSE (ID, ORG_ID)
    ON DELETE RESTRICT
) ENGINE=INNODB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_unicode_ci;


CREATE TABLE IF NOT EXISTS CONSENT_PURPOSE_GROUP_CONSENT (
  CONSENT_ID VARCHAR(255) NOT NULL,
  GROUP_ID   VARCHAR(255) NOT NULL,
  ORG_ID     VARCHAR(255) DEFAULT 'DEFAULT_ORG',

  PRIMARY KEY (CONSENT_ID, GROUP_ID, ORG_ID),

  INDEX idx_group_consent_consent (CONSENT_ID),
  INDEX idx_group_consent_group (GROUP_ID),
  INDEX idx_group_consent_org (ORG_ID),

  CONSTRAINT fk_group_consent_consent
    FOREIGN KEY (CONSENT_ID, ORG_ID)
    REFERENCES CONSENT (CONSENT_ID, ORG_ID)
    ON DELETE CASCADE,

  CONSTRAINT fk_group_consent_group
    FOREIGN KEY (GROUP_ID, ORG_ID)
    REFERENCES CONSENT_PURPOSE_GROUP (ID, ORG_ID)
    ON DELETE RESTRICT
) ENGINE=INNODB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_unicode_ci;

-- Stores user approval status and value for each purpose in a consent
-- Replaces the old CONSENT_PURPOSE_MAPPING when using groups
CREATE TABLE IF NOT EXISTS CONSENT_PURPOSE_APPROVAL (
  CONSENT_ID       VARCHAR(255) NOT NULL,
  GROUP_ID         VARCHAR(255) NOT NULL,
  PURPOSE_ID       VARCHAR(255) NOT NULL,
  IS_USER_APPROVED BOOLEAN NOT NULL DEFAULT FALSE,
  VALUE            JSON DEFAULT NULL,  -- user-provided value for this purpose
  ORG_ID           VARCHAR(255) DEFAULT 'DEFAULT_ORG',

  -- One approval per purpose per consent
  PRIMARY KEY (CONSENT_ID, PURPOSE_ID, ORG_ID),

  INDEX idx_approval_consent (CONSENT_ID, ORG_ID),
  INDEX idx_approval_group (GROUP_ID, ORG_ID),
  INDEX idx_approval_purpose (PURPOSE_ID, ORG_ID),
  INDEX idx_approval_status (IS_USER_APPROVED),

  -- Purpose must belong to the group
  CONSTRAINT fk_approval_group_mapping
    FOREIGN KEY (GROUP_ID, PURPOSE_ID, ORG_ID)
    REFERENCES CONSENT_PURPOSE_GROUP_MAPPING (GROUP_ID, PURPOSE_ID, ORG_ID)
    ON DELETE RESTRICT,

  -- Group must belong to the consent
  CONSTRAINT fk_approval_consent_group
    FOREIGN KEY (CONSENT_ID, GROUP_ID, ORG_ID)
    REFERENCES CONSENT_PURPOSE_GROUP_CONSENT (CONSENT_ID, GROUP_ID, ORG_ID)
    ON DELETE CASCADE
) ENGINE=INNODB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_unicode_ci;
