-- Consent Management API Database Schema
-- Version: 1.0.0
-- Description: Initial schema for consent management system

-- Drop tables if they exist (for clean reinstall)
DROP TABLE IF EXISTS CONSENT_ATTRIBUTE;
DROP TABLE IF EXISTS CONSENT_STATUS_AUDIT;
DROP TABLE IF EXISTS CONSENT_AUTH_RESOURCE;
DROP TABLE IF EXISTS CONSENT_PURPOSE_MAPPING;
DROP TABLE IF EXISTS CONSENT_PURPOSE_ATTRIBUTE;
DROP TABLE IF EXISTS CONSENT_PURPOSE;
DROP TABLE IF EXISTS CONSENT;

-- Main consent table
CREATE TABLE IF NOT EXISTS CONSENT (
  CONSENT_ID            VARCHAR(255) NOT NULL,
  CREATED_TIME          BIGINT NOT NULL,
  UPDATED_TIME          BIGINT NOT NULL,
  CLIENT_ID             VARCHAR(255) NOT NULL,
  CONSENT_TYPE          VARCHAR(64) NOT NULL,
  CURRENT_STATUS        VARCHAR(64) NOT NULL,
  CONSENT_FREQUENCY     INT DEFAULT NULL,
  VALIDITY_TIME         BIGINT DEFAULT NULL,
  RECURRING_INDICATOR   BOOLEAN DEFAULT NULL,
  DATA_ACCESS_VALIDITY_DURATION BIGINT DEFAULT NULL,
  ORG_ID                VARCHAR(255) DEFAULT 'DEFAULT_ORG',
  PRIMARY KEY (CONSENT_ID, ORG_ID),
  INDEX idx_client_id (CLIENT_ID),
  INDEX idx_consent_type (CONSENT_TYPE),
  INDEX idx_current_status (CURRENT_STATUS),
  INDEX idx_created_time (CREATED_TIME),
  INDEX idx_org_id (ORG_ID)
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Authorization resource table
CREATE TABLE IF NOT EXISTS CONSENT_AUTH_RESOURCE (
  AUTH_ID           VARCHAR(255) NOT NULL,
  CONSENT_ID        VARCHAR(255) NOT NULL,
  AUTH_TYPE         VARCHAR(255) NOT NULL,
  USER_ID           VARCHAR(255) DEFAULT NULL,
  AUTH_STATUS       VARCHAR(255) NOT NULL,
  UPDATED_TIME      BIGINT NOT NULL,
  RESOURCES                TEXT DEFAULT NULL,
  ORG_ID            VARCHAR(255) DEFAULT 'DEFAULT_ORG',
  PRIMARY KEY (AUTH_ID, ORG_ID),
  INDEX idx_consent_id (CONSENT_ID),
  INDEX idx_user_id (USER_ID),
  INDEX idx_auth_status (AUTH_STATUS),
  CONSTRAINT FK_CONSENT_AUTH_RESOURCE
    FOREIGN KEY (CONSENT_ID, ORG_ID)
    REFERENCES CONSENT (CONSENT_ID, ORG_ID)
    ON DELETE CASCADE
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Status audit table for tracking consent status changes
CREATE TABLE IF NOT EXISTS CONSENT_STATUS_AUDIT (
  STATUS_AUDIT_ID   VARCHAR(255) NOT NULL,
  CONSENT_ID        VARCHAR(255) NOT NULL,
  CURRENT_STATUS    VARCHAR(64) NOT NULL,
  ACTION_TIME       BIGINT NOT NULL,
  REASON            TEXT DEFAULT NULL,
  ACTION_BY         VARCHAR(255) DEFAULT NULL,
  PREVIOUS_STATUS   VARCHAR(64) DEFAULT NULL,
  ORG_ID            VARCHAR(255) DEFAULT 'DEFAULT_ORG',
  PRIMARY KEY (STATUS_AUDIT_ID, ORG_ID),
  INDEX idx_consent_id (CONSENT_ID),
  INDEX idx_action_time (ACTION_TIME),
  CONSTRAINT FK_CONSENT_STATUS_AUDIT
    FOREIGN KEY (CONSENT_ID, ORG_ID)
    REFERENCES CONSENT (CONSENT_ID, ORG_ID)
    ON DELETE CASCADE
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Consent attributes table for key-value pairs
CREATE TABLE IF NOT EXISTS CONSENT_ATTRIBUTE (
  CONSENT_ID        VARCHAR(255) NOT NULL,
  ATT_KEY           VARCHAR(255) NOT NULL,
  ATT_VALUE         TEXT NOT NULL,
  ORG_ID            VARCHAR(255) DEFAULT 'DEFAULT_ORG',
  PRIMARY KEY (CONSENT_ID, ATT_KEY, ORG_ID),
  INDEX idx_att_key (ATT_KEY),
  CONSTRAINT FK_CONSENT_ATTRIBUTE
    FOREIGN KEY (CONSENT_ID, ORG_ID)
    REFERENCES CONSENT (CONSENT_ID, ORG_ID)
    ON DELETE CASCADE
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Consent purpose table
CREATE TABLE IF NOT EXISTS CONSENT_PURPOSE (
  ID            VARCHAR(255) NOT NULL,
  NAME          VARCHAR(255) NOT NULL,
  DESCRIPTION   VARCHAR(1024) DEFAULT NULL,
  TYPE          VARCHAR(64) NOT NULL DEFAULT 'string',
  ORG_ID        VARCHAR(255) DEFAULT 'DEFAULT_ORG',
  PRIMARY KEY (ID, ORG_ID),
  UNIQUE KEY unique_name_per_org (NAME, ORG_ID),
  INDEX idx_name (NAME),
  INDEX idx_org_id (ORG_ID),
  INDEX idx_type (TYPE)
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Mapping table to link consent with purposes
CREATE TABLE IF NOT EXISTS CONSENT_PURPOSE_MAPPING (
  CONSENT_ID       VARCHAR(255) NOT NULL,
  ORG_ID           VARCHAR(255) DEFAULT 'DEFAULT_ORG',
  PURPOSE_ID       VARCHAR(255) NOT NULL,
  VALUE            JSON DEFAULT NULL,
  IS_USER_APPROVED BOOLEAN DEFAULT FALSE,
  IS_MANDATORY     BOOLEAN NOT NULL DEFAULT TRUE,
  PRIMARY KEY (CONSENT_ID, ORG_ID, PURPOSE_ID),
  INDEX idx_consent_id (CONSENT_ID),
  INDEX idx_purpose_id (PURPOSE_ID),
  INDEX idx_is_user_approved (IS_USER_APPROVED),
  INDEX idx_is_mandatory (IS_MANDATORY),
  INDEX idx_purpose_approved (PURPOSE_ID, IS_USER_APPROVED),
  CONSTRAINT FK_CONSENT_PURPOSE_MAPPING_CONSENT
    FOREIGN KEY (CONSENT_ID, ORG_ID)
    REFERENCES CONSENT (CONSENT_ID, ORG_ID)
    ON DELETE CASCADE,
  CONSTRAINT FK_CONSENT_PURPOSE_MAPPING_PURPOSE
    FOREIGN KEY (PURPOSE_ID, ORG_ID)
    REFERENCES CONSENT_PURPOSE (ID, ORG_ID)
    ON DELETE CASCADE
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Attributes for consent purposes (key/value pairs scoped to purpose + org)
CREATE TABLE IF NOT EXISTS CONSENT_PURPOSE_ATTRIBUTE (
  PURPOSE_ID       VARCHAR(255) NOT NULL,
  ATT_KEY          VARCHAR(255) NOT NULL,
  ATT_VALUE        TEXT NOT NULL,
  ORG_ID           VARCHAR(255) DEFAULT 'DEFAULT_ORG',
  PRIMARY KEY (PURPOSE_ID, ATT_KEY, ORG_ID),
  INDEX idx_att_key_purpose (ATT_KEY),
  CONSTRAINT FK_CONSENT_PURPOSE_ATTRIBUTE_PURPOSE
    FOREIGN KEY (PURPOSE_ID, ORG_ID)
    REFERENCES CONSENT_PURPOSE (ID, ORG_ID)
    ON DELETE CASCADE
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
